import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";
import { getAuth } from "firebase/auth";
import { getStorage } from "firebase/storage"; // 1. Import getStorage

// This token is required for the frontend to securely log in as an admin.
// It should be generated by your backend in a real application.
export const __initial_auth_token = "eyJhbGciOiAiUlMyNTYiLCAidHlwIjogIkpXVCIsICJraWQiOiAiOTNmZjlmYjViNDIwMzcyMTU3YTRkNTlhNjk0NGM3YzY2Y2Q3YTE1YiJ9.eyJpc3MiOiAiZmlyZWJhc2UtYWRtaW5zZGstZmJzdmNAbG9uZG9uLWdvdXJtZXQuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCAic3ViIjogImZpcmViYXNlLWFkbWluc2RrLWZic3ZjQGxvbmRvbi1nb3VybWV0LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwgImF1ZCI6ICJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaWRlbnRpdHkuaWRlbnRpdHl0b29sa2l0LnYxLklkZW50aXR5VG9vbGtpdCIsICJ1aWQiOiAiYWRtaW4tdXNlciIsICJpYXQiOiAxNzYwODc4OTUzLCAiZXhwIjogMTc2MDg4MjU1M30.VQ43OTKxFYXhqUROOx4mjSstfGzn6JBC545FVutXQRQMEKpsOvuhuBKJ1G8aQmexFDfnWMRdDK8ukkRmS3PxoY0KexJZCut3DEjuhmhD8O0Vjukl4zyxD5Pa1NSXbTeezwh1oVLlFn-dOrgzIzyfc-PYLdODMzaQOIFC3Z3cXn2L4KKAx6ALtM92GJrj283wUQtocFQjjqaCJ6kywVHy9pKI5C7sxqdiY1pSRNmgituwiZv7w-GFCvdcsEleNHAi6eWU0IvZ1ClDoUcl9MSFObdNOwXYOWoVrYA3GJ-tN61hOGAK6sHENw8AAFoWltUU0T9N0GbLBUAIUwweCYg_MQ";

// This is the public configuration for your web app. It is safe to be in frontend code.
const firebaseConfig = {
  apiKey: "AIzaSyC_m-_6qHoYYqI0jQNceWMYZiKPEt4665I",
  authDomain: "london-gourmet.firebaseapp.com",
  projectId: "london-gourmet",
  storageBucket: "london-gourmet.appspot.com",
  messagingSenderId: "1092458598991",
  appId: "1:1092458598991:web:20ee6533f961c6009a903a",
  measurementId: "G-GHMJ0CN4BB"
};

// Initialize Firebase for the client-side app
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);
const auth = getAuth(app);
const storage = getStorage(app); // 2. Initialize Storage

// 3. Export storage along with db and auth
export { db, auth, storage };


